-- 1. Verifica registrazione geometria (facoltativo, commentato)
--SELECT * FROM USER_SDO_GEOM_METADATA
--WHERE TABLE_NAME = 'GEO_DATI_INTERFEROMETRICI_SPATIAL' AND COLUMN_NAME = 'GEOM_SDO';

-- 2. Ricostruzione dell’indice spaziale
BEGIN
  EXECUTE IMMEDIATE 'ALTER INDEX GEO_DATI_INTERF_SP_GIDX REBUILD PARAMETERS(''LAYER_GTYPE=POINT'')';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Indice spaziale non ricostruito: ' || SQLERRM);
END;
/

-- 3. Riabilitazione degli indici normali
BEGIN
  EXECUTE IMMEDIATE 'ALTER INDEX IDX_GEO_INTERF_ORIGINE_DATO ENABLE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER INDEX GEO_DATI_INTERF_SP_CODE_IDX ENABLE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- 4. Creazione indice JSON (con fallback)
BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX IDX_GEO_JSON_VALID';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE INDEX IDX_GEO_JSON_VALID
    ON GEO_DATI_INTERFEROMETRICI_SPATIAL (DATI_VARIABILI)
    INDEXTYPE IS JSON
  ';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Indice JSON non creato: ' || SQLERRM);
END;
/

-- 5. Abilitazione parallelismo sulla tabella
ALTER TABLE GEO_DATI_INTERFEROMETRICI_SPATIAL PARALLEL 4;

-- 6. Aggiornamento statistiche
BEGIN
  DBMS_STATS.GATHER_TABLE_STATS(
    ownname => 'DWHADM',
    tabname => 'GEO_DATI_INTERFEROMETRICI_SPATIAL',
    cascade => TRUE
  );
END;
/
